# Default (English)

nav:
  home: Home
  archives: Archives
  about: About
  categories: Categories
  tags: Tags

search:
  placeholder: Search...
  no_results: No results found

post:
  posted: Posted on
  updated: Updated on
  read_more: Read More
  words: words
  min_read: min read
  toc: Table of Contents

pagination:
  prev: Prev
  next: Next

archive:
  title: Archive

error_404:
  title: Page Not Found
  description: Sorry, the page you are looking for does not exist.
  back_home: Back to Home

comments:
  title: Comments

footer:
  powered_by: Powered by Hexo
  theme: Theme
